name: dlb
channels:
  # - conda-forge
  # - nvidia
  # - pytorch
dependencies:
  - python
  - numpy
  - pandas
  - tqdm
  - scikit-learn
  - scikit-learn-intelex
  - scipy
  - opencv
  - PyWavelets
  - nvidia::cudatoolkit
  - pytorch::pytorch
  - pytorch::torchvision
# Note - follow this with pip install thop
# Added: sudo apt-get install ffmpeg libsm6 libxext6
